name: Activities Service CI for Development

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run local MongoDB for test
        run: sudo systemctl start mongod.service

      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Package install
        run: yarn install --frozen-lockfile --production=false

      - name: Run unit tests
        run: yarn jest --ci --collect-coverage
        env:
          DB_URL: mongodb://localhost:27017/test
          DB_OPTIONS: minSize=5&poolSize=20
          SECRET: secret

      - name: App build
        run: yarn build